# Task 2: Network Discovery and Analysis

---

## Q1: Getting started with nmap

The Docker-based environment was started using `docker compose up -d`, which created the required services and internal networks. The relevant Docker bridge network used in this task was `networksecurity_mitm`.

Host discovery was performed using `nmap` to identify which hosts were active within the subnet. A ping scan revealed two active hosts:

* `172.31.0.2` – **alice**
* `172.31.0.3` – **bob**

Each host was then scanned individually using TCP SYN scanning and service/version detection:

```bash
sudo nmap -sS -sV -Pn <IP>
```

The scan results showed:

* **alice (172.31.0.2):** No open application-level ports were detected. The host was reachable but did not expose any services.
* **bob (172.31.0.3):** Port `80/tcp` was open and running a Python-based HTTP service (`SimpleHTTPServer`).

Based on these results, bob acts as a server providing an HTTP service, while alice functions as a client-only container. Nmap was able to correctly identify both the open port and the running service.

---

## Q2: Capturing the voting traffic

Network traffic was captured using Wireshark on the Docker bridge interface associated with the `networksecurity_mitm` network.

During the capture, traffic was generated by inter-container communication and scanning activity. The following protocols were observed:

* **ICMP**, used for connectivity testing between containers
* **TCP**, used for port scanning and application communication
* **HTTP**, associated with the Python HTTP service running on bob

All captured traffic occurred within the internal Docker bridge network, confirming that communication stayed inside the private network and did not leave the host system.

---

## Q3: Unique votes

Based on the network analysis, vote uniqueness is not enforced at the network level but rather through application-level mechanisms.

Since the traffic is transmitted in plaintext within the internal network, an attacker with access to the same network could potentially:

* Intercept application requests
* Replay previously captured requests
* Spoof client behavior by modifying request data

As a result, the concept of “unique votes” can be bypassed if uniqueness relies solely on client-side identifiers or unprotected application logic. This could negatively affect the integrity of the voting results.

---

## Q4: nmap aggressive scan

An aggressive scan was performed using the following command:

```bash
sudo nmap -A <IP>
```

This enabled:

* OS detection
* Service and version detection
* Default NSE scripts
* Traceroute functionality

In this small Docker-based environment with minimal exposed services, only limited additional traffic was visible in Wireshark. This behavior is expected due to the small scale of the network.

Aggressive scans generate more intrusive traffic than basic scans and may impact services or trigger security monitoring systems in larger or production environments.

---

## Q5: Promiscuous mode

Wireshark’s promiscuous mode allows a network interface to capture all packets it can observe, not only packets explicitly addressed to the host.

This mode is particularly important in shared or bridged environments such as Docker bridge networks, where multiple containers communicate over the same virtual interface. Promiscuous mode enables effective traffic analysis, troubleshooting, and security monitoring.

In switched networks, promiscuous mode alone does not guarantee visibility of all traffic, but it remains a critical feature for network engineers when analyzing shared network segments.

